### ISSUE TITLE
Getting Started needs to be updated to use fake directly

### ISSUE THREAD

**Issue by davecarpie** [SaturnFramework/docs#29]
The Getting Started docs say after creating a new Saturn template project, you should run `build.sh`.
However, the v0.9.0 template doesn't come with scripts. Users should just use paket/fake directly

**Comment by iammiles** [comment]
I was able to follow the directions from PR #28 to get the starter template built and running. Not sure if there's something else planned, but I think we should consider getting working documentation pushed up to the live site up sooner than later. As someone who is getting started with .Net Core and F#, it was a bit of a disappointment to have to dig through PRs to get the starter template working.

**Comment by Krzysztof-Cieslak** [comment]
#28 got merged

**Comment by iammiles** [comment]
Fantastic! Thank you, Krzysztof. I wasn't expecting such a fast turnaround.
