### ISSUE TITLE
Pipeline / accept{Json, Xml, Html, Multipart}

### ISSUE THREAD

**Issue by ChrSteinert** [SaturnFramework/docs#31]
The [Pipeline doc page](https://saturnframework.org/docs/api/pipeline/#acceptjson) says, that the accept{Json, Xml, Html, Multipart} Pipeline Helpers accept on the header `ContentType`, when they are accepting the header `Accept`.
Am I missing something or does it just state the wrong header key?

Happy to send a PR, if this is indeed the other way around.

**Comment by ChrSteinert** [comment]
See https://github.com/ChrSteinert/docs-2/commit/57c62c505d3b5a0bf092822b54f97130c7f9a4b7 for my wording suggestion.

**Comment by Krzysztof-Cieslak** [comment]
No, I've just probably made some copy-paste error. Suggested fix looks good to me 👍
