### ISSUE TITLE
The guide page still not use the latest github file

### ISSUE THREAD

**Issue by ScottHuangZL** [SaturnFramework/docs#8]
The guide page still not use the latest github file

For example: 
https://saturnframework.github.io/docs/guides/adding-pages/
To begin, create a Hello folder inside the src folder Inside the folder,

**Need change to**

To begin, create a Hello folder inside the **src\SaturnSample** folder Inside the folder,

Another thing, I find **need update the SaturnSample.fsproj file too**. I have create one pull request, **please merge it** to resolve the issue for newbies.

Thanks.

**Comment by Krzysztof-Cieslak** [comment]
Done
